# Setup
#title:               The Personal Website of Ben Tonelli
#tagline:             'A Work in Progress!'
#description:         'Updated 7/21'
url:                 https://bentonelli.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ben Tonelli
  email:             btonelli@ucla.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
